### ISSUE TITLE
Fuel SimVars not available.

### ISSUE THREAD

**Issue by Frohrer** [Pomax/msfs-simconnect-api-wrapper#18]
Hello, love this API. I am having trouble getting any fuel related simvars, such as FUEL TOTAL CAPACITY or FUEL TOTAL QUANTITY.

Error: Cannot get SimVar: "FUEL TOTAL CAPACITY" unknown.

**Comment by Pomax** [comment]
Interesting, looks like the entire https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Aircraft_SimVars/Aircraft_Fuel_Variables.htm collection is missing! I'll get those added.

**Comment by Pomax** [comment]
V2.1 pushed to npm, let me know if things are still failing now that fuel vars are supposed =D

**Comment by Frohrer** [comment]
Great, thank you!On Sep 8, 2023, at 8:24 PM, Pomax ***@***.***> wrote:﻿
V2.1 pushed to npm, let me know if things are still failing now that fuel vars are supposed =D
