### ISSUE TITLE
Handle reconnect to MSFS after closing the sim

### ISSUE THREAD

**Issue by Nordicdesign** [Pomax/msfs-simconnect-api-wrapper#20]
Hi,

First of all thanks for the wrapper, I'm new to simconnect and this is much easier to use!!! 🙏

I'm not sure if this is handled already, but I haven't seen it on my tests. I'm creating a client that logs flights, and after it has connected to MSFS, when I close the sim it doesn't go back to the previous state of trying to connect. 

I suppose that if I'm able to ascertain whether the sim has closed (not sure what event/simvar would that be!), I could call the connect function again, but it'd be great if the `connect` method had some kind of `onConnectionLost` as well as on connect and retry.

Cheers,
Alex

**Comment by Pomax** [comment]
Hah, I was thinking of the same thing, since I'm currently uplifting https://github.com/Pomax/are-we-flying and have run into wanting it to reconnect if MSFS crashes and I restart it =P

**Comment by Pomax** [comment]
Added an `autoReconnect`, with v2.2.0 pushed out to npm.

**Comment by Nordicdesign** [comment]
Works perfectly! 
You may want to clear the console log though 😀 
https://github.com/Pomax/msfs-simconnect-api-wrapper/blob/20f3be347e1d0ad429834e1dc60f03118e02623d/msfs-api.js#L66

**Comment by Pomax** [comment]
now _there's_ an idea...

**Comment by Pomax** [comment]
v2.2.1 pushed out.
