### ISSUE TITLE
Interact with AI Objects

### ISSUE THREAD

**Issue by ilbonte** [Pomax/msfs-simconnect-api-wrapper#27]
It's not clear to me if I can interact with [AI Objects](https://github.com/EvenAR/node-simconnect#ai-objects) using this library. If yes, how can i do it?

For example i'd like to use [AICreateSimulatedObject](https://docs.flightsimulator.com/html/Programming_Tools/SimConnect/API_Reference/AI_Object/SimConnect_AICreateSimulatedObject.htm)

Thanks for the support :)

PS: i took a look at your "are we flying",  is awesome!

**Comment by Pomax** [comment]
hm, probably not, this only wraps the simvar/events side of SimConnect, so you might need to use [node-simconnect](https://github.com/EvenAR/node-simconnect) for that directly.

As for the doc, I'm hopefully almost done rewriting everything so it's going to get quite an overhaul too (just need to iron out some fun crashes with the new autoland code)

**Comment by ilbonte** [comment]
Understood! 
Great work anyway
