### ISSUE TITLE
RecvException 3

### ISSUE THREAD

**Issue by Pomax** [Pomax/msfs-simconnect-api-wrapper#9]
Seeing a bunch of these:

```
Connection failed, retrying in 5 seconds
Connected to MSFS
RecvException { exception: 3, sendId: 6, index: 3 }
RecvException { exception: 3, sendId: 10, index: 3 }
RecvException { exception: 3, sendId: 14, index: 3 }
RecvException { exception: 3, sendId: 18, index: 3 }
RecvException { exception: 3, sendId: 22, index: 3 }
RecvException { exception: 3, sendId: 25, index: 3 }
```

Exceotion 3 is a `SIMCONNECT_EXCEPTION_UNRECOGNIZED_ID` error, so let's find out what's triggering them, and fix it.

**Comment by Pomax** [comment]
haven't seen this pop up in a while. Closing

**Comment by Nordicdesign** [comment]
Was going to raise an issue about this and found this on google :) 
I am getting something like `RecvException { exception: 3, sendId: 17, index: 3 }` if I launch the app I'm building _before_ MSFS has fully loaded. 

It seems like the connect call happens a few moments before simconnect is actually ready to go, as indicated on this comment here: https://www.avsim.com/forums/topic/635462-warning-simconnect-error-detected-exception-received-3/?tab=comments#comment-4985360

If I run my app _after_ MSFS has loaded it works fine. 

The workaround I found at the moment is to add a 10s delay after `onConnect` is triggered, to let MSFS load completely. But this is just a hack, it will depend on each system.

**Comment by Pomax** [comment]
I mean honestly, they exception does nothing, so there's no _real_ need to use a timeout, but it'd be nice to move all those exceptions over to a special handler... want to file a new issue?

**Comment by Nordicdesign** [comment]
In my case I run a `schedule` right after connecting, and if that fails it never picks up any of the data I need, hence the delay to ensure the schedule run. Probably could code it differently to avoid that but not sure how right now. If I see it is an issue I'll raise it.

**Comment by Pomax** [comment]
Hm, yeah that definitely sounds something to file a new issue for, with some STR (steps to reproduce) and some self-contained minimal code that shows it happening.

**Comment by Pomax** [comment]
I've filed https://github.com/Pomax/msfs-simconnect-api-wrapper/issues/23
